### ISSUE TITLE
If trusted, would this allow any block to break blocks?

### ISSUE THREAD

**Issue by TheFlash787** [Shadows-of-Fire/PlaneFix#1]
Hey! 

So since you're using `[Minecraft]` which is quite a generic name for a fake player, is this used by any other mods? For example, if I used `/trust [Minecraft]` in my claim, would there be mods out there that would be able to change things inside of the claim?

Wouldn't it be better to have the fake player be something like `[PlaneFix]` so that when that is trusted, it will *only* definitely allow the annihilation plane to break blocks, without letting other things do that?

Thank you.

**Comment by Shadows-of-Fire** [comment]
Maybe?  No clue what else uses that fakeplayer.
Anyhow, 1.12 and this mod are unsupported, so no changes will ever be made.
